# Generated by Django 5.0.2 on 2024-07-19 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(null=True, related_name='volunteered_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
