# Generated by Django 5.0.2 on 2024-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironswords', '0005_user_allow_notifications_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finished_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Profession', 'לעסוק במקצוע ובכישורים שלי'), ('Friends', 'להתנדב עם חברים'), ('Distance', 'להתנדב קרוב לבית')], default=None, max_length=30, null=True),
        ),
    ]
