# Generated by Django 5.0.2 on 2024-03-25 09:29

import ironswords.models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironswords', '0006_user_finished_onboarding_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Profession', 'לעסוק במקצוע ובכישורים שלי'), ('Friends', 'להתנדב עם חברים'), ('Distance', 'קרוב לבית'), ('Organization', 'החמ"ל שלי')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='volunteer_frequency',
            field=models.IntegerField(blank=True, choices=[(ironswords.models.user_model.VolunteerFrequency['LESS_THAN_ONCE'], 1), (ironswords.models.user_model.VolunteerFrequency['MORE_THAN_ONCE'], 2), (ironswords.models.user_model.VolunteerFrequency['WHENEVER'], 3), (ironswords.models.user_model.VolunteerFrequency['ONCE_A_WEEK'], 0)], default=None, null=True),
        ),
    ]
