# Generated by Django 5.0.2 on 2024-03-25 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironswords', '0007_alter_user_most_important_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('contact_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Friends', 'להתנדב עם חברים'), ('Organization', 'החמ"ל שלי'), ('Distance', 'קרוב לבית'), ('Profession', 'לעסוק במקצוע ובכישורים שלי')], default=None, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('recurring', models.BooleanField(default=False)),
                ('max_volunteers', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('duration', models.DurationField(default=2)),
                ('volunteers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ironswords.organization')),
            ],
        ),
    ]
