# Generated by Django 5.0.2 on 2024-03-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironswords', '0010_alter_application_status_alter_user_most_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined'), ('Canceled', 'Canceled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Distance', 'קרוב לבית'), ('Organization', 'החמ"ל שלי'), ('Friends', 'להתנדב עם חברים'), ('Profession', 'לעסוק במקצוע ובכישורים שלי')], default=None, max_length=30, null=True),
        ),
    ]
