# Generated by Django 5.0.2 on 2024-03-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironswords', '0011_alter_application_status_alter_user_most_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Profession', 'לעסוק במקצוע ובכישורים שלי'), ('Friends', 'להתנדב עם חברים'), ('Distance', 'קרוב לבית'), ('Organization', 'החמ"ל שלי')], default=None, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'event')},
        ),
    ]
