# Generated by Django 5.0.2 on 2024-07-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironswords', '0013_alter_event_volunteers_alter_user_most_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Profession', 'לעסוק במקצוע ובכישורים שלי'), ('Distance', 'קרוב לבית'), ('Organization', 'החמ"ל שלי'), ('Friends', 'להתנדב עם חברים')], default=None, max_length=30, null=True),
        ),
    ]
