# Generated by Django 5.0.2 on 2024-07-09 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironswords', '0014_alter_user_gender_alter_user_most_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shift_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_managed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, null=True, related_name='volunteered_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Organization', 'החמ"ל שלי'), ('Profession', 'לעסוק במקצוע ובכישורים שלי'), ('Distance', 'קרוב לבית'), ('Friends', 'להתנדב עם חברים')], default=None, max_length=30, null=True),
        ),
    ]
