# Generated by Django 5.0.2 on 2024-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_gender_alter_user_most_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Distance', 'קרוב לבית'), ('Profession', 'לעסוק במקצוע ובכישורים שלי'), ('Organization', 'החמ"ל שלי'), ('Friends', 'להתנדב עם חברים')], default=None, max_length=30, null=True),
        ),
    ]
