# Generated by Django 5.0.2 on 2024-08-21 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0006_alter_user_most_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Distance', 'קרוב לבית'), ('Profession', 'לעסוק במקצוע ובכישורים שלי'), ('Friends', 'להתנדב עם חברים'), ('Organization', 'החמ"ל שלי')], default=None, max_length=30, null=True),
        ),
    ]
