# Generated by Django 5.0.2 on 2024-07-21 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_most_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Distance', 'קרוב לבית'), ('Profession', 'לעסוק במקצוע ובכישורים שלי'), ('Organization', 'החמ"ל שלי'), ('Friends', 'להתנדב עם חברים')], default=None, max_length=30, null=True),
        ),
    ]
