# Generated by Django 5.0.2 on 2024-08-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0013_alter_user_most_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Organization', 'החמ"ל שלי'), ('Profession', 'לעסוק במקצוע ובכישורים שלי'), ('Distance', 'קרוב לבית'), ('Friends', 'להתנדב עם חברים')], default=None, max_length=30, null=True),
        ),
    ]
