# Generated by Django 5.0.2 on 2024-08-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_gender_alter_user_most_important_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='most_important',
            field=models.CharField(blank=True, choices=[('Distance', 'קרוב לבית'), ('Friends', 'להתנדב עם חברים'), ('Profession', 'לעסוק במקצוע ובכישורים שלי'), ('Organization', 'החמ"ל שלי')], default=None, max_length=30, null=True),
        ),
    ]
